# 服务配置
server:
  port: 8080
  tomcat:
    connection-timeout: 120s

spring:

  # 使用配置文件
  profiles:
    active: local

  # 配置druid数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 30000
      filters: stat,wall,log4j2
      validationQuery: select 'x'
      stat-view-servlet:
        enabled: true

  # jpa配置
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        session_factory:
          statement_inspector: com.isxcode.star.backend.config.JpaTenantInterceptor

  # mvc配置
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**

  # h2数据库配置
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  # 定时调度
  quartz:
    scheduler-name: spark-yun-quartz-scheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.dataSource: quartzDataSource

  # 缓存
  cache:
    type: simple

# openapi
springdoc:
  api-docs:
    path: /swagger-ui/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.isxcode.star

# admin用户访问
spark-yun:
  admin-url:
    - /swagger-ui/** # http://localhost:8080/swagger-ui/index.html
    - /h2-console/** # http://localhost:8080/h2-console
    - /druid/** # http://localhost:8080/druid/index.html
  anonymous-url:
    - /
    - /static/**
    - /favicon.ico
    - /login
    - /**/open/**
    - /vip/api/custom/**
  jwt-key: spark-yun
  aes-slat: spark-yun
  resources-path: /resources
  agent-tar-gz-dir: /spark-yun
  agent-bin-dir: /spark-yun/bin
  default-agent-port: 30177
  expiration-min: 1440

