spark-yun:
  agent-tar-gz-dir: /Users/ispong/Isxcode/spark-yun/spark-yun-dist/build/distributions
  agent-bin-dir: /Users/ispong/Isxcode/spark-yun/spark-yun-dist/src/main/bin
  default-agent-port: 30177

spring:

  # 支持h2数据库
#  flyway:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/.h2/data
#    user: root
#    password: ispong123
#    locations: classpath:db/migration/h2/

  # 支持mysql数据库
  flyway:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:30306/zhiqingyun
    user: root
    password: ispong123
    locations: classpath:db/migration/mysql/

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/.h2/data
#    username: root
#    password: ispong123

  # 数据源配置 http://localhost:8080/h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:30306/zhiqingyun
    username: root
    password: ispong123

